// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGpDmX9HuaTQAlfk26GrleTK1_vHSystU',
    appId: '1:390173527714:web:d6c5e4921e1d7bf51311fb',
    messagingSenderId: '390173527714',
    projectId: 'agritayo-608e7',
    authDomain: 'agritayo-608e7.firebaseapp.com',
    storageBucket: 'agritayo-608e7.firebasestorage.app',
    measurementId: 'G-ZLQKY82JNB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpEmbOym_Nbr7oRGbqOkwtX1Ot1ZwlRns',
    appId: '1:390173527714:android:1e1637841dbf3c831311fb',
    messagingSenderId: '390173527714',
    projectId: 'agritayo-608e7',
    storageBucket: 'agritayo-608e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtu-dO1g5-EavQsOSHQs7dWNxxORCQGSs',
    appId: '1:390173527714:ios:ed7f3cd462267da41311fb',
    messagingSenderId: '390173527714',
    projectId: 'agritayo-608e7',
    storageBucket: 'agritayo-608e7.firebasestorage.app',
    iosBundleId: 'com.example.agritayo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtu-dO1g5-EavQsOSHQs7dWNxxORCQGSs',
    appId: '1:390173527714:ios:ed7f3cd462267da41311fb',
    messagingSenderId: '390173527714',
    projectId: 'agritayo-608e7',
    storageBucket: 'agritayo-608e7.firebasestorage.app',
    iosBundleId: 'com.example.agritayo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGpDmX9HuaTQAlfk26GrleTK1_vHSystU',
    appId: '1:390173527714:web:34da3c72759ce24d1311fb',
    messagingSenderId: '390173527714',
    projectId: 'agritayo-608e7',
    authDomain: 'agritayo-608e7.firebaseapp.com',
    storageBucket: 'agritayo-608e7.firebasestorage.app',
    measurementId: 'G-22GPP0T2X5',
  );
}
